version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            ssh ${SSH_USER}@${SSH_HOST} "mkdir -p ~/code/rewbot"
            scp -oStrictHostKeyChecking=no -r ~/project/* ${SSH_USER}@${SSH_HOST}:code/rewbot/.
            export slack_token=${slack_token}
            ssh -oSendEnv=slack_token ${SSH_USER}@${SSH_HOST} "cd ~/code/rewbot; make slack_token=${slack_token}"
