version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            ssh ${SSH_USER}@${SSH_HOST} "mkdir ~/code/"
            scp -oStrictHostKeyChecking=no -r ~/project ${SSH_USER}@${SSH_HOST}:code/.
            #ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
